# general
batch_size: 128
eval_batch_size: 200
input_size: 32
# embd_shape is for the Resnet, backbone
embd_shape: 128
#iom_res50_twostage_triplet -- only two stage with triplet loss
#iom_res50_twostage_triplet and quantization loss -- triplet loss + quantization loss, this in another config file
sub_name: 'margin_online'
backbone_type: 'MobileNetV2' # 'ResNet50', 'MobileNetV2'
head_type: IoMHead # 'ArcHead', 'NormHead'
is_ccrop: False # central-cropping or not

#margin loss
alpha: 50
beta_0: 0.6

# for metric learning, we have 1. triplet_semi batch_hard_triplet 2. batch_all_triplet_loss 3. batch_all_arc_triplet_loss 4 margin_loss
loss_fun: 'margin_loss'
num_classes: 10
# I generate 1 milion triplets
num_samples: 3000000
epochs: 50
base_lr: 0.01
w_decay: !!float 5e-4
save_steps: 1000