# general
batch_size: 128
eval_batch_size: 200
input_size: 32
# embd_shape is for the Resnet,VGG16 backbone
embd_shape: 128
sub_name: 'margin_online'
backbone_type: 'AlexNet' # 'ResNet50', 'MobileNetV2' AlexNet
is_ccrop: False # central-cropping or not

#margin loss
alpha: 50
beta_0: 0.6

# for metric learning, we have 1. triplet_semi batch_hard_triplet 2. batch_all_triplet_loss 3. batch_all_arc_triplet_loss 4 margin_loss
loss_fun: 'margin_loss'
num_classes: 10
# I generate 1 milion triplets
num_samples: 50000
epochs: 50
base_lr: 0.1
w_decay: !!float 5e-4
save_steps: 5000